services:
  web:
    build: .
    container_name: codeigniter
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_USER: ci4
      MYSQL_PASSWORD: ci4pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: